version: '3.1'

services:
  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306